package com.powerx.electricityservice.soapservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-17T00:51:26.801-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.customerdetails.customerservice.com/", name = "ServicePlanWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicePlanWS {

    @WebMethod
    @RequestWrapper(localName = "getServicePlan", targetNamespace = "http://webservice.customerdetails.customerservice.com/", className = "com.powerx.electricityservice.soapservice.GetServicePlan")
    @ResponseWrapper(localName = "getServicePlanResponse", targetNamespace = "http://webservice.customerdetails.customerservice.com/", className = "com.powerx.electricityservice.soapservice.GetServicePlanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.powerx.electricityservice.soapservice.ServicePlan> getServicePlan();
}
